# Generated by Django 2.0 on 2018-12-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0009_auto_20181208_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_availability',
            old_name='room_type',
            new_name='select_rooms',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_type',
            new_name='select_rooms',
        ),
        migrations.RemoveField(
            model_name='check_availability',
            name='maxno',
        ),
    ]
