# Generated by Django 2.0 on 2018-12-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0010_auto_20181211_1106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check_Availability',
            new_name='Check',
        ),
    ]
