# Generated by Django 2.0 on 2018-12-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0011_auto_20181211_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='select_rooms',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='select_rooms',
            new_name='room_type',
        ),
    ]
