# Generated by Django 2.0 on 2018-12-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0012_auto_20181211_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('cust_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check_Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_In', models.DateField()),
                ('check_Out', models.DateField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('cust_id', models.IntegerField()),
                ('room_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('check_In', models.DateField()),
                ('check_Out', models.DateField()),
                ('total_cost', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='check',
            name='room',
        ),
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.AddField(
            model_name='cancel',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Display'),
        ),
    ]
