# Generated by Django 2.0 on 2018-12-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0013_auto_20181211_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel',
            name='room_no',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Display',
        ),
    ]
