# Generated by Django 2.0 on 2018-12-12 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0014_auto_20181211_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('cust_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('cust_id', models.IntegerField()),
                ('room_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('check_In', models.DateField()),
                ('check_Out', models.DateField()),
                ('total_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserve_Room',
            fields=[
                ('room_no', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('credit_card', models.IntegerField()),
                ('debit_card', models.IntegerField()),
                ('check_In', models.DateField()),
                ('check_Out', models.DateField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Check_Availability')),
            ],
        ),
        migrations.DeleteModel(
            name='Cancel',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='max_numbers',
            new_name='avaliable_rooms',
        ),
        migrations.RemoveField(
            model_name='room',
            name='total_rooms',
        ),
        migrations.AddField(
            model_name='display',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Reserve_Room'),
        ),
        migrations.AddField(
            model_name='cancle',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Display'),
        ),
    ]
