# Generated by Django 2.0 on 2018-12-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0016_auto_20181212_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='max_numbers',
        ),
    ]
