# Generated by Django 2.0 on 2018-12-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0017_remove_room_max_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bed_option',
        ),
    ]
