# Generated by Django 2.0 on 2018-12-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0018_remove_room_bed_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available_roomNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
