# Generated by Django 2.0 on 2018-12-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0021_auto_20181212_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='total_rooms',
            new_name='total_booking_rooms',
        ),
    ]
