# Generated by Django 2.0 on 2018-12-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0022_auto_20181212_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available_roomNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
