# Generated by Django 2.0 on 2018-12-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0025_auto_20181212_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancle',
            name='room_no',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='total_booking_rooms',
            new_name='total_rooms',
        ),
        migrations.DeleteModel(
            name='Cancle',
        ),
        migrations.DeleteModel(
            name='Display',
        ),
    ]
