# Generated by Django 2.0 on 2018-12-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0026_auto_20181212_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('check_In', models.DateField()),
                ('check_Out', models.DateField()),
                ('total_cost', models.FloatField()),
                ('cust_id', models.IntegerField()),
            ],
        ),
    ]
